### ISSUE TITLE
Weird command name

### ISSUE THREAD

**Issue by jamilraichouni** [hatedMe/rc-beautify#2]
Hi!

When you create a new extension via `yo code` it will have exactly one example command named `extension.sayHello`.

This is still the name of the contributed command in your extension.
Be so kind and give the command a more explanatory name like `rc.beautify` of similar!

This is in your `package.json` file:

```json
"commands": [
    {
        "command": "extension.sayHello",
        "title": "Beautify React Javascript TypeScript"
    }
],
```

Thanks,
Jamil

**Comment by Enchufadoo** [comment]
Hi, I came for this, also the default keyboard shortcut (ctrl + B) conflicts with vscode toggle sidebar shortcut:

` { "key": "ctrl+b",                "command": "extension.sayHello" },`

**Comment by jamilraichouni** [comment]
no reaction :-(

**Comment by jamilraichouni** [comment]
> Hi, I came for this, also the default keyboard shortcut (ctrl + B) conflicts with vscode toggle sidebar shortcut:
> 
> ` { "key": "ctrl+b", "command": "extension.sayHello" },`

That is a separate topic and shall be described in an own issue.
